# Generated by Django 5.1.1 on 2026-05-22 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS historial;",
            "DROP SCHEMA IF EXISTS historial;"
        ),
        migrations.CreateModel(
            name='HistorialNavegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('visto_en', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Navegación',
                'verbose_name_plural': 'Historiales de Navegación',
                'db_table': 'historial"."HistorialNavegacion',
                'ordering': ['-visto_en'],
                'indexes': [models.Index(fields=['usuario', 'visto_en'], name='HistorialNa_usuario_60449c_idx'), models.Index(fields=['content_type', 'object_id'], name='HistorialNa_content_4d449a_idx')],
            },
        ),
    ]
