# Generated by Django 5.1.1 on 2026-07-17 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_restaurante_es_destacado_restaurante_rating_avg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Restaurante',
                'verbose_name_plural': 'Tipos de Restaurantes',
                'db_table': 'restaurantes.TipoRestaurante',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tipo_restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurantes', to='restaurantes.tiporestaurante'),
        ),
    ]
