# Generated by Django 5.1.1 on 2026-09-10 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS notificaciones;",
            "DROP SCHEMA IF EXISTS notificaciones;"
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('lugar', 'Lugar Turístico'), ('evento', 'Evento'), ('alerta', 'Alerta'), ('promocion', 'Promoción'), ('recordatorio', 'Recordatorio')], default='sistema', max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('icono', models.URLField(blank=True, null=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('enlace', models.CharField(blank=True, max_length=500, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones"."Notificacion',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('notificaciones_sistema', models.BooleanField(default=True)),
                ('notificaciones_lugares', models.BooleanField(default=True)),
                ('notificaciones_eventos', models.BooleanField(default=True)),
                ('notificaciones_alertas', models.BooleanField(default=True)),
                ('notificaciones_promociones', models.BooleanField(default=True)),
                ('notificaciones_recordatorios', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('no_molestar_inicio', models.TimeField(blank=True, null=True)),
                ('no_molestar_fin', models.TimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Notificación',
                'verbose_name_plural': 'Preferencias de Notificaciones',
                'db_table': 'notificaciones"."PreferenciaNotificacion',
            },
        ),
    ]
