# Generated by Django 5.1.1 on 2026-04-30 02:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamientos', '0001_initial'),
        ('eventos', '0001_initial'),
        ('lugaresturisticos', '0001_initial'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'db_table': 'gestiones.RedSocial',
            },
        ),
        migrations.CreateModel(
            name='ValoracionComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('tipo_entidad', models.CharField(choices=[('lugar_turistico', 'Lugar Turístico'), ('evento', 'Evento'), ('alojamiento', 'Alojamiento'), ('restaurante', 'Restaurante')], max_length=20)),
                ('id_entidad', models.PositiveIntegerField()),
                ('texto', models.TextField(blank=True, default='')),
                ('valoracion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('interacciones', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Valoracion Comentario',
                'verbose_name_plural': 'Valoraciones Comentarios',
                'db_table': 'gestiones.ValoracionComentario',
            },
        ),
        migrations.CreateModel(
            name='LugarTuristicoRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('url_perfil', models.URLField()),
                ('lugar_turistico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='lugaresturisticos.lugarturistico')),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lugares_turisticos', to='gestiones.redsocial')),
            ],
            options={
                'verbose_name': 'Lugar Turistico Red Social',
                'verbose_name_plural': 'Lugares Turisticos Redes Sociales',
                'db_table': 'gestiones.LugarTuristicoRedSocial',
            },
        ),
        migrations.CreateModel(
            name='EventoRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('url_perfil', models.URLField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='eventos.evento')),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gestiones.redsocial')),
            ],
            options={
                'verbose_name': 'Evento Red Social',
                'verbose_name_plural': 'Eventos Redes Sociales',
                'db_table': 'gestiones.EventoRedSocial',
            },
        ),
        migrations.CreateModel(
            name='AlojamientoRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('url_perfil', models.URLField()),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='alojamientos.alojamiento')),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alojamientos', to='gestiones.redsocial')),
            ],
            options={
                'verbose_name': 'Alojamiento Red Social',
                'verbose_name_plural': 'Alojamientos Redes Sociales',
                'db_table': 'gestiones.AlojamientoRedSocial',
            },
        ),
        migrations.CreateModel(
            name='RestauranteRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('url_perfil', models.URLField()),
                ('red_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantes', to='gestiones.redsocial')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes_sociales', to='restaurantes.restaurante')),
            ],
            options={
                'verbose_name': 'Restaurante Red Social',
                'verbose_name_plural': 'Restaurantes Redes Sociales',
                'db_table': 'gestiones.RestauranteRedSocial',
            },
        ),
    ]
