# Generated by Django 5.1.1 on 2026-04-30 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestiones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracioncomentario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valoraciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lugarturisticoredsocial',
            unique_together={('lugar_turistico', 'red_social')},
        ),
        migrations.AlterUniqueTogether(
            name='eventoredsocial',
            unique_together={('evento', 'red_social')},
        ),
        migrations.AlterUniqueTogether(
            name='alojamientoredsocial',
            unique_together={('alojamiento', 'red_social')},
        ),
        migrations.AlterUniqueTogether(
            name='restauranteredsocial',
            unique_together={('restaurante', 'red_social')},
        ),
        migrations.AddIndex(
            model_name='valoracioncomentario',
            index=models.Index(fields=['tipo_entidad', 'id_entidad'], name='gestiones.V_tipo_en_6a80f6_idx'),
        ),
        migrations.AddIndex(
            model_name='valoracioncomentario',
            index=models.Index(fields=['usuario'], name='gestiones.V_usuario_01fa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='valoracioncomentario',
            index=models.Index(fields=['valoracion'], name='gestiones.V_valorac_1a873a_idx'),
        ),
    ]
