# Generated by Django 5.1.1 on 2026-05-01 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestiones', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlaceRedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('url_perfil', models.URLField()),
            ],
            options={
                'verbose_name': 'Enlace Red Social',
                'verbose_name_plural': 'Enlaces Redes Sociales',
                'db_table': 'gestiones.EnlaceRedSocial',
            },
        ),
        migrations.AlterUniqueTogether(
            name='alojamientoredsocial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='alojamientoredsocial',
            name='alojamiento',
        ),
        migrations.RemoveField(
            model_name='alojamientoredsocial',
            name='red_social',
        ),
        migrations.AlterUniqueTogether(
            name='eventoredsocial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eventoredsocial',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='eventoredsocial',
            name='red_social',
        ),
        migrations.AlterUniqueTogether(
            name='lugarturisticoredsocial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lugarturisticoredsocial',
            name='lugar_turistico',
        ),
        migrations.RemoveField(
            model_name='lugarturisticoredsocial',
            name='red_social',
        ),
        migrations.AlterUniqueTogether(
            name='restauranteredsocial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='restauranteredsocial',
            name='red_social',
        ),
        migrations.RemoveField(
            model_name='restauranteredsocial',
            name='restaurante',
        ),
        migrations.RemoveIndex(
            model_name='valoracioncomentario',
            name='gestiones.V_tipo_en_6a80f6_idx',
        ),
        migrations.RenameField(
            model_name='valoracioncomentario',
            old_name='id_entidad',
            new_name='object_id',
        ),
        migrations.RemoveField(
            model_name='valoracioncomentario',
            name='tipo_entidad',
        ),
        migrations.AddField(
            model_name='valoracioncomentario',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='valoracioncomentario',
            index=models.Index(fields=['content_type', 'object_id'], name='gestiones.V_content_2d3359_idx'),
        ),
        migrations.AddField(
            model_name='enlaceredsocial',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='enlaceredsocial',
            name='red_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='gestiones.redsocial'),
        ),
        migrations.DeleteModel(
            name='AlojamientoRedSocial',
        ),
        migrations.DeleteModel(
            name='EventoRedSocial',
        ),
        migrations.DeleteModel(
            name='LugarTuristicoRedSocial',
        ),
        migrations.DeleteModel(
            name='RestauranteRedSocial',
        ),
        migrations.AddIndex(
            model_name='enlaceredsocial',
            index=models.Index(fields=['content_type', 'object_id'], name='gestiones.E_content_0fdc3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enlaceredsocial',
            unique_together={('content_type', 'object_id', 'red_social')},
        ),
    ]
