# Generated by Django 5.1.1 on 2026-05-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='rating_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
