# Generated by Django 5.1.1 on 2026-04-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('imagen', models.ImageField(upload_to='media/imagenes/lugares-turisticos')),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('precio_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('sitio_web', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'LugarTuristico',
                'verbose_name_plural': 'LugaresTuristicos',
                'db_table': 'lugaresturisticos.LugarTuristico',
            },
        ),
    ]
