# Generated by Django 5.1.1 on 2026-04-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugaresturisticos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarturistico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes/lugares-turisticos'),
        ),
    ]
