# Generated by Django 5.1.1 on 2026-05-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugaresturisticos', '0002_alter_lugarturistico_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'TipoLugarTuristico',
                'verbose_name_plural': 'TiposLugaresTuristicos',
                'db_table': 'lugaresturisticos.TipoLugarTuristico',
            },
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='tipo_lugar_turistico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lugaresturisticos.tipolugarturistico'),
        ),
    ]
