# Generated by Django 5.1.1 on 2026-05-22 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugaresturisticos', '0003_tipolugarturistico_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS lugaresturisticos;",
            "DROP SCHEMA IF EXISTS lugaresturisticos;"
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='rating_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImagenLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='lugaresturisticos.lugarturistico')),
            ],
            options={
                'verbose_name': 'Imagen Lugar',
                'verbose_name_plural': 'Imágenes Lugar',
                'db_table': 'lugaresturisticos"."ImagenLugar',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='lugaresturisticos.lugarturistico')),
            ],
            options={
                'verbose_name': 'Etiqueta Lugar',
                'verbose_name_plural': 'Etiquetas Lugar',
                'db_table': 'lugaresturisticos"."EtiquetaLugar',
                'unique_together': {('lugar', 'etiqueta')},
            },
        ),
    ]
