# Generated by Django 5.1.1 on 2026-05-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS noticias;",
            "DROP SCHEMA IF EXISTS noticias;"
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('extracto', models.TextField(blank=True, default='')),
                ('cuerpo', models.TextField()),
                ('categoria', models.CharField(choices=[('eventos', 'Eventos'), ('alertas', 'Alertas'), ('consejos', 'Consejos'), ('cultura', 'Cultura')], max_length=50)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('nivel_alerta', models.CharField(blank=True, choices=[('info', 'Información'), ('advertencia', 'Advertencia'), ('peligro', 'Peligro')], max_length=20, null=True)),
                ('es_destacada', models.BooleanField(default=False)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticias"."Noticia',
                'ordering': ['-publicado_en'],
            },
        ),
    ]
