# Generated by Django 5.1.1 on 2026-04-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/imagenes/alojamientos'),
        ),
    ]
