# Generated by Django 5.1.1 on 2026-05-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_apellido_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
