# Generated by Django 5.1.1 on 2026-05-22 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS mascota;",
            "DROP SCHEMA IF EXISTS mascota;"
        ),
        migrations.CreateModel(
            name='ConsejoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('texto', models.CharField(max_length=500)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5)),
                ('activo', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Consejo Mascota',
                'verbose_name_plural': 'Consejos Mascota',
                'db_table': 'mascota"."ConsejoMascota',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='ConsejoMasc_content_6b144a_idx')],
            },
        ),
    ]
